#!/usr/bin/perl
##
## db_groups_cvs_history_days.pl 
##
## NIGHTLY SCRIPT
##
## Pulls the parsed CVS datafile (generated by cvs_history_days_parse.pl ) from the
## cvs server, and parses it into the database for Repository History of Groups
##
## $Id
##
use strict;
use Time::Local;
use POSIX qw( strftime );

my ($year, $month, $day, $day_begin, $day_end);
my $verbose = 1;

$|=0 if $verbose;

   ## Set the time to collect stats for
if ( $ARGV[0] ) {

          ## Start at midnight n days ago
        $day_begin = timegm( 0, 0, 0, (gmtime( time() - ($ARGV[0] * 86400) ))[3,4,5] );

} else {

           ## Start at midnight 30 days ago.
        $day_begin = timegm( 0, 0, 0, (gmtime( time() - (30 * 86400) ))[3,4,5] );
           ## go until midnight yesterday.
        $day_end = timegm( 0, 0, 0, (gmtime( time() ))[3,4,5] );

	$year	= strftime("%Y", gmtime( $day_begin ) );
	$month	= strftime("%m", gmtime( $day_begin ) );
	$day	= strftime("%d", gmtime( $day_begin ) );

}

print "Parsing the information into the database starting at $year-$month-$day.\n" if $verbose;

print "cd /usr/local/httpd/SF2.5/utils/underworld-root;./db_groups_cvs_history.pl $year $month $day\n" if $verbose;
system("cd /usr/local/httpd/SF2.5/utils/underworld-root;./db_groups_cvs_history.pl $year $month $day");
print "Done.\n" if $verbose;

##
## EOF
##
