#!/usr/bin/perl
#
#  Dump LDAP database 
#  by pfalcon@users.sourceforge.net 2000-10-18
#  $Id: ldap-dump,v 1.1 2003/11/12 16:09:03 helix Exp $
#

require("include.pl");  # Include all the predefined functions
&parse_local_inc;

$cmd = "${ldap_prefix}ldapsearch -LLL -D '$sys_ldap_bind_dn' -w $sys_ldap_passwd -b '$sys_ldap_base_dn' '(objectclass=*)'";
system($cmd);
